### ISSUE TITLE
Gzip middleware - Revisiting urls gives empty response body

### ISSUE THREAD

**Issue by binBASH** [gin-gonic/contrib#11]
When trying to access urls the first request returns "hello world" for / which is expected.
However when revisiting the url the result body is empty and no hello world :-(
Tested with firefox, google chrome, cURL

Example code:

```go
package main

import(
    "github.com/gin-gonic/gin"
    "github.com/gin-gonic/contrib/gzip"
)

func main() {
    r := gin.Default()
    r.Use(gzip.Gzip(gzip.DefaultCompression))
    r.GET("/", func(c *gin.Context) {
        c.String(200, "hello world")
    })
    r.GET("/json", func(c *gin.Context) {
        c.JSON(200, gin.H{"message": "hello world"})
    })
    r.Run(":8080")
}
```

**Comment by shuoli84** [comment]
Is this project dead? Gzip middleware literally not working without the fix.

**Comment by javierprovecho** [comment]
Sorry for delay, protect is alive, I'm looking actively at main project issues, but I'll jump again to contrib as soon as I can.

—
Enviado desde Mailbox

**Comment by javierprovecho** [comment]
I've tested with cURL and it works, but when you make a request from a browser, everything fails.

**Comment by stunti** [comment]
@javierprovecho I just pull everything and it breaks if you use master branch of gzip but my change seems to work. I tried both curl and with firefox and chrome. (I use the example provided for simplicity in the example folder). I am happy to help test it. Which branch of gin did you use? I tried with master.

**Comment by stunti** [comment]
@javierprovecho Any news on that? have you tried again with and without the pull request in a browser?
Thanks

**Comment by binBASH** [comment]
for me provided patch works btw.

**Comment by javierprovecho** [comment]
@binBASH @stunti @shuoli84 please check gin-gonic/gin#204. Thank you in advance.

**Comment by javierprovecho** [comment]
@binBASH this bug is not appearing anymore with latest version of Gin, v0.5 RC. That implies to close this issue and your pull request, and an apology for the delay in my answers to you. Thank you for your effort.

**Comment by javierprovecho** [comment]
@binBASH @stunti @shuoli84 sorry for huge delay. Discard any previous message, I was able to check it against Gin v0.5 RC successfully. Thank you all.
