### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by 0x4139** [gin-gonic/contrib#115]
Is this still maintained? if not can you add rights to merge pull requests and fix bugs?

**Comment by Skarlso** [comment]
I guess that means no? :/ It would be nice to transfer bug fixing rights then. 👍

**Comment by tboerger** [comment]
The team has increased now and we are working on the open issues and pull requests. For this repository we plan to move the middlewares to separate repos at https://github.com/gin-contrib and keep this repo just for backward compat.

**Comment by Skarlso** [comment]
Thanks for the response @tboerger! Very glad to hear this. I do love gin, I also realise that it's an open project, and people are basically working on it in their free time. Very awesome stuff guys. Very awesome indeed.

**Comment by gplume** [comment]
Personally I can't ever ima-gin-e working without GIN, all my projects 
and work's applications are based on it...
Everything seems stable to me, I don't see any urgency to develop more 
although it's always reassuring in some ways.
Except when a big update break things up!!
I second the comment below, great job guys and thanks for sharing.

**Comment by javierprovecho** [comment]
I suggest to `watch` gins' repos and read/chat in [`gitter`](https://gitter.im/gin-gonic/gin) where you can contact us directly.

closing this, and thanks for your interest 😉
