### ISSUE TITLE
No  Access-Control-Allow-Origin in generatePreflightHeaders?

### ISSUE THREAD

**Issue by goofansu** [gin-gonic/contrib#119]
I cannot see this option return back to preflight request. So it always says `No 'Access-Control-Allow-Origin' header is present on the requested resource. `.

**Comment by javierprovecho** [comment]
@goofansu please check "new" middlewares at https://github.com/gin-contrib. 

https://github.com/gin-gonic/contrib will be preserved but no longer maintained.
