### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by Simoron** [gin-gonic/contrib#133]
Hi, 

cannot use c (type *"gopkg.in/gin-gonic/gin.v1".Context) as type *"github.com/gin-gonic/gin".Context in argument to "github.com/gin-contrib/sessions".

**Comment by appleboy** [comment]
@Simoron Please change `gopkg.in/gin-gonic/gin.v1` to `github.com/gin-gonic/gin`

ref: https://github.com/gin-gonic/gin/issues/828
