### ISSUE TITLE
Add the authorization middleware

### ISSUE THREAD

**Issue by hsluoyz** [gin-gonic/contrib#137]
Hi, I have created an authorization middleware for Gin here: https://github.com/casbin/gin-authz

I saw the organization for plugins at: https://github.com/gin-contrib, And I want this plugin to be listed there, the ``authz`` repo name would be good. But I don't have rights to create any repos there. Could you please tell me how to proceed? Thanks!

**Comment by appleboy** [comment]
@hsluoyz I created new repo https://github.com/gin-contrib/authz and invite you as collaborators. Thanks for your contributions.

**Comment by hsluoyz** [comment]
@appleboy  Thanks!

**Comment by hsluoyz** [comment]
Hi @appleboy , can you switch on Travis CI on this plugin, I don't have the rights here:

![image](https://cloud.githubusercontent.com/assets/3787410/26536520/5ccb612a-446a-11e7-9867-7ecc4ff644e8.png)

The link is: https://travis-ci.org/gin-contrib/authz

Thanks!

**Comment by appleboy** [comment]
@hsluoyz Done
