### ISSUE TITLE
Fix logrus import in ginrus (due to rename)

### ISSUE THREAD

**Issue by arddor** [gin-gonic/contrib#140]
The github path to logrus was recently changed from `github.com/Sirupsen/logrus` to `github.com/sirupsen/logrus`. 
Packages have to adjust that otherwise they will no longer work with logrus: https://github.com/sirupsen/logrus/issues/553

**Comment by appleboy** [comment]
fix in #141

**Comment by Xiol** [comment]
Can this be merged please?

**Comment by appleboy** [comment]
@Xiol Done
