### ISSUE TITLE
Add the rollbar middleware

### ISSUE THREAD

**Issue by easonlin404** [gin-gonic/contrib#144]
Hi, I have created rollbar middleware to integrate with [rollbar](https://rollbar.com/) error monitoring for Gin here: https://github.com/easonlin404/rollbar

And this middleware can be to listed or transferred at gin-contrib org? Please give me any advice and how to proceed? Thanks!

**Comment by appleboy** [comment]
@easonlin404 I will create a new repo and add you as maintainer. Please push your commits and delete repo from your profile.

**Comment by easonlin404** [comment]
@appleboy I have push to https://github.com/gin-contrib/rollbar Thank a lot.
