### ISSUE TITLE
JWT force token expiration

### ISSUE THREAD

**Issue by denisdpc** [gin-gonic/contrib#148]
Using the "example.go" in JWT, and I'd like to know if there is a way to force token expiration
I'd like to use it when user logout, for example.

Thanks

**Comment by qichengzx** [comment]
@denisdpc It looks like there is no destroy for token in both of JWT and github.com/dgrijalva/jwt-go , I think maybe you can use token.SignedString again with a expired time like time.Now().Unix()-1
