### ISSUE TITLE
[SOLVED] gin-contrib has gone?

### ISSUE THREAD

**Issue by seblegall** [gin-gonic/contrib#164]
Hi,

I was woking with the cors middleware (https://github.com/gin-contrib/cors) for 2 days, but today it seems the whole "gin-contrib" user, referenced many times in this repo, has gone.

Any clue? I'm not sure to understand the link between this repo and the gin-contrib user.

**Comment by inful** [comment]
Same problem, seems like it's gone.

**Comment by javierprovecho** [comment]
Hi@seblegall and @inful , I've received a notification from Github telling me that the org has been flagged, I'm looking into the cause.

cc @appleboy

**Comment by javierprovecho** [comment]
Hi @seblegall and @inful , seems that github.com/gin-contrib has been restored. Thanks.

I didn't received a message about the cause of the flagging, so I'll keep the issue open a few more hours.

**Comment by appleboy** [comment]
@javierprovecho thanks. I didn't receive any message about github.com/gin-contrib org

**Comment by seblegall** [comment]
Seems to be working again. Thx.

**Comment by javierprovecho** [comment]
Message from GitHub:
```
[...] automated security mechanisms incorrectly triggered [...]
```
