### ISSUE TITLE
`time` attribute duplicated in logrus/ginrus entry

### ISSUE THREAD

**Issue by thoeni** [gin-gonic/contrib#168]
@oryband I can see that the entry that is created here appends a time attribute:
https://github.com/gin-gonic/contrib/blob/master/ginrus/ginrus.go#L45

As far as I can see every log entry from logrus already has a `time` key. Entry implements `Stringer`, so the user could customise the timestamp in there.

https://github.com/sirupsen/logrus/blob/master/entry.go#L34-L35

As a consequence I end up having two `time` attributes, one comes from `logrus` and one from `ginrus`. Any suggestion on how to tackle this? Should we overload the signature to allow a handler without that attribute to keep backwards compatibility? 

Also, with the json encoder the label shows as `fields.time` because of the duplicate entry from logrus...

**Comment by oryband** [comment]
@thoeni @hassansin sorry, i'm no longer maintaining ginrus.

**Comment by appleboy** [comment]
@thoeni Please try the https://github.com/gin-contrib/logger
