### ISSUE TITLE
static middleware will not compile - c.Abort does not contain the proper number of arguments

### ISSUE THREAD

**Issue by adamjcook** [gin-gonic/contrib#17]
I am noticing that, when attempting to `go get` the "static" middleware, I am presented with the following error in the console:

`../../../../gin-gonic/contrib/static/static.go:86: not enough arguments in call to c.Abort`

After some investigation, it appears that the GoDeps manifest is locking the gin version to a very old commit in which there was a single code argument required for the Abort method. See https://github.com/gin-gonic/gin/blob/c224bf82111883dbe354edf9376642f615b7248e/gin.go#L312

The current state of static.go seems to be written without the argument present (https://github.com/gin-gonic/contrib/blob/master/static/static.go#L86) which is correct according to the most recent commit to gin (https://github.com/gin-gonic/gin/blob/develop/context.go#L119).

Therefore, I am assuming that the GoDeps is out of date for some reason or that the "static" middleware was written against the develop branch... Please let me know if you would like a pull request on this issue. I can make one.

P.S. I am also noticing this same issue in the contrib/secure middleware code, but I will submit a separate issue for that one since they are different packages.

**Comment by javierprovecho** [comment]
@adamjcook thank you for discovering this. I forgot completely about GoDeps. You can submit a pull request with updated GoDeps if you wish. I'll review it as soon as available. I'll update the other GoDeps' packages also.

**Comment by Iceyer** [comment]
Abort accpet a http status code as input.

https://github.com/Iceyer/contrib/commit/811ff47e4bc4c9b324baf2ffb38732fcd218939c

**Comment by rogierlommers** [comment]
When will this be merged?

**Comment by javierprovecho** [comment]
Please check gin-gonic/gin#204. Thank you in advance.

**Comment by rogierlommers** [comment]
@javierprovecho thanks! Very much appreciated...

**Comment by javierprovecho** [comment]
@rogierlommers @adamjcook @WinterM @Iceyer sorry for this. There was an unsync between master and develop at main repository of Gin. By the time of publishing v0.5 RC, it was solved, however you will need to update your Gin version to latest. You can do it like:

```bash
go get -u github.com/gin-gonic/gin
```

If that's not working, please delete folder from `$GOPATH` and `go get ...` again. Also I want to remember that Gin only supports Go version >= 1.3.

If you need any assistance, please drop a response.

**Comment by janos** [comment]
Hi, after removing c.Abort(), if any handler continues to process the request, it ends with warning "Headers were already written!" and invalid (combined) response. 

Basic example:
r := gin.New()
r.Use(static.Serve("/static"), static.LocalFile("/tmp", false))
r.GET("/:category/:post", func(c ...

Breaking the chain is important in this case and it is fixing this issue.
