### ISSUE TITLE
how to get x-response-time and write it in the http header with gin?

### ISSUE THREAD

**Issue by snowdream** [gin-gonic/contrib#184]
how to get x-response-time and write it in the http header with gin?
like express and koa.

https://github.com/expressjs/response-time
https://github.com/koajs/response-time

**Comment by appleboy** [comment]
https://github.com/gin-gonic/gin/blob/2e5a7196cce94e085625d166e7f2cf9f99a1edf0/context.go#L753

**Comment by dtest11** [comment]
https://github.com/dtest11/reponse/blob/1f462b27a8930673eb85868e1bdc402a488693db/reponse_time_test.go#L8
