### ISSUE TITLE
[QUESTION] sessions: Session `Get` method

### ISSUE THREAD

**Issue by mrfoe7** [gin-gonic/contrib#187]
Hi, everyone!
Why are sessions method `Get` return interface{} instead string?
[code](https://github.com/gin-gonic/contrib/blob/master/sessions/sessions.go#L39)

**Comment by shirejoni** [comment]
who said that all value that can be in  a session  is type of string?
```
mysession.Values["username"]="hossein" // string
mysession.Values["id"] = 10; // integer

```
```

**Comment by mrfoe7** [comment]
@shirejoni thanks for your answer but it does not actual
