### ISSUE TITLE
the github page were 404 not found

### ISSUE THREAD

**Issue by jeyrce** [gin-gonic/contrib#216]
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/33649388/158720656-104c3658-2647-4bc4-9469-9d73088e9150.png">

click the link will get 404. should be matained

**Comment by appleboy** [comment]
I am not owner so can't fix the link on readme. cc @javierprovecho

**Comment by appleboy** [comment]
new website: https://gin-gonic.com/

**Comment by appleboy** [comment]
duplicated of https://github.com/gin-gonic/contrib/issues/192
