### ISSUE TITLE
InMemoryStore cut off response

### ISSUE THREAD

**Issue by exu** [gin-gonic/contrib#57]
I have problem with in memory cache, when response is read from cache 
it returns only:  

```
    </body>
</html>
```

Have you any idea what could be wrong?

I've configured my cache for handler like below:

```
app := gin.Default()
store := cache.NewInMemoryStore(time.Second)
app.GET("/", cache.CachePage(store, time.Minute, handler.Index))
```

(handler.Index is standard gin handler )

**Comment by exu** [comment]
It looks like in recent gin response is written in []byte stream, so cache entry is overwritten for each chunk of data, and this response under cache key is last chunk of data.

**Comment by exu** [comment]
I have the same for redis cache backend.

**Comment by Sawa2012** [comment]
fxgsm.fbng;mgfnm;kgfdhn/m,;fhgd,/

**Comment by appleboy** [comment]
@exu This cache package has been abandoned on 2016-12-07. Please use [gin-contrib/cache](https://github.com/gin-contrib/cache) instead.

**Comment by appleboy** [comment]
See https://github.com/gin-gonic/contrib/blob/master/cache/README.md
