### ISSUE TITLE
ginrus example broken

### ISSUE THREAD

**Issue by bobbo** [gin-gonic/contrib#78]
The ginrus example is currently broken. Logrus appears to have a new API (use `Logger.Out = output` instead of `Logger.SetOutput(output)` and there is an un-used import.

**Comment by turtlemonvh** [comment]
:+1:

**Comment by oryband** [comment]
Hi @bobbo and @turtlemonvh . I'm the one who PRed ginrus support in the first place at #40 . I don't have time to fix this right now, sorry. Feel free to submit a PR.

**Comment by turtlemonvh** [comment]
Gotcha @oryband.  PR is here: https://github.com/gin-gonic/contrib/pull/101
