### ISSUE TITLE
Url alias middleware

### ISSUE THREAD

**Issue by aboukirev** [gin-gonic/contrib#9]
I needed to maintain URL rewriting from arbitrary path like "/help" to a path handled by router "/node/1234".  Here is what I cam up with:
```go
func UrlRewrite(ignore string) gin.HandlerFunc {
	return func(c *gin.Context) {
		if !strings.HasPrefix(c.Request.URL.Path, ignore) {
			path := DecodeAlias(c.Request.URL.Path)
			if path != c.Request.URL.Path {
				c.Request.URL.Path = path
				c.Engine.ServeHTTP(c.Writer, c.Request)
				c.Abort(-1)
				return
			}
		}
		c.Next()
	}
}
``` 
The DecodeAlias() above performs a lookup in URL alias table and returns either a decoded path or original one. The "ignore" parameter is to avoid decoding alias on static content.  The idea here is to force router to restart handling with the decoded path, match to a different set of handlers, and process as necessary without sending redirect to the browser.  The browser keeps seeing nice original URL. One may consider it a "server redirect."

Some of you may recognize Drupal URL aliasing method.  So far this worked for me.  I wonder if anyone has a better idea and whether it deserves to be added to contrib in some form.

**Comment by javierprovecho** [comment]
@aboukirev sorry for delay.

Looks nice but for me I'm not sure if this should be pushed to contrib. If you could add some examples of how to use, it will be better prepared for push.

**Comment by tmm1** [comment]
Thanks for sharing this technique. It's quite useful since httprouter is limited in its ability to match paths.
