### ISSUE TITLE
When using go get I get no build able source code 

### ISSUE THREAD

**Issue by joeblew99** [gin-gonic/contrib#98]
I know this is picky, but it screws up tooling for a large team.
It also breaks the newer censoring tools like gvt.

Any recommendations for how to force a pull ?
Go get -u -D  ??

**Comment by iwanbk** [comment]
@joeblew99 
how about `go get  github.com/gin-gonic/contrib/...`?

**Comment by joeblew99** [comment]
go get -u -d ... works.

-d forces a download even if its not go.
